### ISSUE TITLE
Clicking on an internal link doesn't update the URL in the address bar

### ISSUE THREAD

**Issue by moggers87** [oggcamp/oggcamp-jekll#9]
Steps to reproduce:

1. Go to oggcamp.org
2. Click the link to "Talk Guidelines"
3. Copy and paste the URL to a friend

Expected results:

* The URL will send your friend to the talk guidelines page

Actual results:

* The URL sends your friend to the main page

**Comment by moggers87** [comment]
OK, so oggcamp.org is actually serving the github pages inside an frame. Surely there's a better way?

**Comment by moggers87** [comment]
Might be helpful: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by JonTheNiceGuy** [comment]
We've just not got around to transferring it from Fabsh properly. It's one of those things on the to-do list. Also we have about 6 domains (.com .org .net ogg.camp and a handful of others) that all need to either redirect or cname. We've just not got around to it yet.

**Comment by moggers87** [comment]
I think this has been fixed now
